service: serverless-greeting

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

