version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    ports:
      - "4500:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
